# Generated by Django 4.2.4 on 2023-08-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('IECcode', models.CharField(max_length=60)),
                ('gstno', models.CharField(max_length=18)),
                ('panno', models.CharField(max_length=18)),
                ('Authsignatory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('igid', models.BigAutoField(primary_key=True, serialize=False)),
                ('igroupname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='itemType',
            fields=[
                ('iid', models.BigAutoField(primary_key=True, serialize=False)),
                ('HSNcode', models.CharField(max_length=50)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.item')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('salesOrderno', models.CharField(max_length=90)),
                ('orderdate', models.DateField()),
                ('supplierOrderDate', models.DateField()),
                ('ValidityPeriod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ports',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('portname', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.country')),
            ],
        ),
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('shipmentid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Blno', models.CharField(max_length=90)),
                ('SOBdate', models.DateTimeField()),
                ('isshipped', models.BooleanField()),
                ('Fpod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_as_fpod', to='web.ports')),
                ('LoadPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_as_load_port', to='web.ports')),
                ('POR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_as_por', to='web.ports')),
                ('Pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_as_pod', to='web.ports')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_as_orderid', to='web.order')),
                ('shippingline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_as_sobdate', to='web.order')),
            ],
        ),
        migrations.CreateModel(
            name='shippingline',
            fields=[
                ('slid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('IECcode', models.CharField(max_length=60)),
                ('country_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.country')),
            ],
        ),
        migrations.CreateModel(
            name='shipmentDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentdetail_as_item', to='web.shipment')),
                ('shipmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipmentdetail_as_shipmentid', to='web.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('Qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.itemtype')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='FPOD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_fpod', to='web.ports'),
        ),
        migrations.AddField(
            model_name='order',
            name='LoadPort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_laod_port', to='web.ports'),
        ),
        migrations.AddField(
            model_name='order',
            name='POD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_pod', to='web.ports'),
        ),
        migrations.AddField(
            model_name='order',
            name='POR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_por', to='web.ports'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='ft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_ft', to='web.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_supplier', to='web.supplier'),
        ),
    ]
