# Generated by Django 4.2.4 on 2023-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_itemtype_hsncode_alter_ports_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='type',
            field=models.CharField(choices=[('1', 'dry'), ('2', 'sea')], default=1, max_length=3),
        ),
    ]
